name: build

on:
  push:
    paths-ignore:
    - LICENSE
    - README.md
  pull_request:
    paths-ignore:
    - LICENSE
    - README.md
  workflow_dispatch:

jobs:
  build:
    name: build with sm${{ matrix.sm_version }} on ${{ matrix.os_short }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - windows-latest

        sm_version:
          - "1.10"
          - "1.11"
          - "latest"
          
        include:
          - sm_version: "1.10"
            sm_branch: "1.10-dev"

          - sm_version: "1.11"
            sm_branch: "1.11-dev"

          - sm_version: latest
            sm_branch: master

          - os: ubuntu-20.04
            os_short: linux
          
          - os: windows-latest
            os_short: windows
     
    steps:
      - name: Prepare env
        shell: bash
        run: |
          echo "GITHUB_SHA_SHORT=${GITHUB_SHA::7}" >> $GITHUB_ENV
          
      - name: Install (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y clang g++-multilib
          echo "CC=clang" >> $GITHUB_ENV
          echo "CXX=clang++" >> $GITHUB_ENV

      - name: Setting up xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: Getting SourceMod ${{ matrix.sm_version }}
        uses: actions/checkout@v4
        with:
          repository: alliedmodders/sourcemod
          ref: ${{ matrix.sm_branch }}
          path: sourcemod-${{ matrix.sm_version }}
          submodules: recursive
          
      - name: Getting hl2sdk-l4d2
        uses: actions/checkout@v4
        with:
          repository: alliedmodders/hl2sdk
          ref: l4d2
          path: hl2sdk-l4d2

      - name: Getting hl2sdk-l4d
        uses: actions/checkout@v4
        with:
          repository: alliedmodders/hl2sdk
          ref: l4d
          path: hl2sdk-l4d
      
      - name: Getting safetyhook
        uses: actions/checkout@v4
        with:
          repository: alliedmodders/safetyhook
          ref: main
          path: safetyhook
          
      - name: Getting own repository
        uses: actions/checkout@v4
        with:
          path: src
          
      - name: Compiling ${{ github.event.repository.name }} files
        shell: bash
        working-directory: src
        run: |
          xmake f -p ${{ matrix.os_short }} --SMPATH=../sourcemod-${{ matrix.sm_version }} --HL2SDKPATH=../hl2sdk-l4d2 --HL2SDKNAME=l4d2 --SAFETYHOOKPATH=../safetyhook
          xmake -rv cutlrbtreefix
          xmake f -p ${{ matrix.os_short }} --SMPATH=../sourcemod-${{ matrix.sm_version }} --HL2SDKPATH=../hl2sdk-l4d --HL2SDKNAME=l4d --SAFETYHOOKPATH=../safetyhook
          xmake -rv cutlrbtreefix
          
      - name: Uploading package
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-sm${{ matrix.sm_version }}-${{ matrix.os_short }}-${{ env.GITHUB_SHA_SHORT }}
          path: src/release
